### ISSUE TITLE
flowdiagramr cannot be installed for R 4.2.2

### ISSUE THREAD

**Issue by svd09** [andreashandel/flowdiagramr#26]
Hi, Thank you for this package. It is exactly what I need to create the flowcharts. I tried to install the package, but I get this error:

Warning in install.packages :
  package ‘flowdiagramr’ is not available for this version of R

**Comment by andreashandel** [comment]
The package is not yet on CRAN, it needs to be installed from GitHub. I updated the documentation to make that clear and show how to do it.

**Comment by svd09** [comment]
Thank you. I installed it. Best.
