### ISSUE TITLE
Add aesthetic arguments to `make_diagram()`

### ISSUE THREAD

**Issue by atredennick** [andreashandel/flowdiagramr#4]
Add a suite of aesthetics users can stipulate:

- node color
    * either scalar or vector to be recycled
- node font 
   * style (?)
   * color
- arrow color (by type: interaction or "main")
- arrow width (by type: interaction or "main")
- others???

**Comment by andreashandel** [comment]
if color vector and user does not supply grid, recycling will be based on mbmodel object. if user does supply grid for variable placement, color should be applied/recycled maybe row-wise based on matrix/DF entries?

If we allow font specification for nodes (good idea if not too hard) should also allow for flow labels. Maybe even more important than font type is font size?

Other maybe feature:
Scaling factor for compartment box (e.g. there is a default, if user says boxsize = 0.8 it's going to 80% of the default, etc.)

**Comment by atredennick** [comment]
Completed:

- node fill and outline colors
- node label text size
- node label color
- flow label text size
- flow label text color
- flow color

Was able to create this glorious monster:
```
make_diagram(df_list = diagram_dfs, 
                             node_outline_color = "red",
                             node_fill_color = "blue",
                             node_text_color = "orange",
                             node_text_size = 5,
                             flow_text_color = "green",
                             flow_text_size = 20,
                             main_arrow_color = "green")
```
![image](https://user-images.githubusercontent.com/2903862/109882550-4c4b9780-7c37-11eb-89f4-9c2a3607ac54.png)

We might want not want to go down the font type rabbit hole. It gets difficult when people have different font names. E.g., one cannot simply put "Arial" as the `family` argument in ggplot: https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2.

Scaling the compartment box requires re-scaling the arrows too so that they connect. This will have to be done in the data frames creation function OR make a new function that fudges everything according to the scaling.

**Comment by atredennick** [comment]
The arguments can also be used responsibly to make pleasing diagrams.

![image](https://user-images.githubusercontent.com/2903862/110043907-79667b80-7d05-11eb-9100-110b0c7b8380.png)
