### ISSUE TITLE
External flows in and out at 45 deg angles

### ISSUE THREAD

**Issue by atredennick** [andreashandel/flowdiagramr#6]
See title.

**Comment by andreashandel** [comment]
ok to play with angles (maybe 30 easier?). or always have start of arrow (for outflows) on right middle of box, end at bottom height? inflow somewhere from top-left, outflow somewhere top-right seems ideal. otherwise flexible, whatever looks/works best.

**Comment by atredennick** [comment]
![image](https://user-images.githubusercontent.com/2903862/109212248-849d3280-776c-11eb-93b8-85e439ca73ce.png)
