### ISSUE TITLE
input structure for main diagram functions

### ISSUE THREAD

**Issue by andreashandel** [andreashandel/flowdiagramr#9]
I suggest we have the main input structure to be fed into the main diagram prep function to be a simple list. I sketched something out in the auxiliary/modelexample.R file. Details can be changed, just wanted to sketch out the overall idea/approach. We can discuss more.

**Comment by atredennick** [comment]
I took a look at your example. I like this idea. And it should be easy to use code we already have to make the helper function for mbmodels.

**Comment by atredennick** [comment]
@andreashandel, what do you think about making the flow inputs a list with names like S_flows? Might be easier to match everything up if parsing list names rather than parsing object names themselves. For example, instead of:

```
varlabels = c("S")
S_flows = c("+n",      "-m*S")
diag_input_list = list(varlabels = varlabels, S_flows = S_flows)
```

it would be:

```
varlabels = c("S")
flows = list(S_flows = c("+n",      "-m*S"))
diag_input_list = list(varlabels = varlabels, flows = flows)
```

**Comment by atredennick** [comment]
I deleted my last comment. I realized I had misread your code.

**Comment by atredennick** [comment]
@andreashandel See commit 67c0a0d for possible resolution. Input list looks like following for simple SIR:

```
$varlabels
[1] "S" "I" "R"

$varnames
[1] "Susceptible" "Infected"    "Recovered"  

$flows
$flows$S_flows
[1] "-b*S*I" "+w*R"   "+n"     "-m*S"  

$flows$I_flows
[1] "+b*S*I" "-g*I"   "-m*I"  

$flows$R_flows
[1] "+g*I" "-w*R" "-m*R"
```
